name: RoodCore
version: 2.0
description: R00DCore
author: cooltimmetje
main: me.cooltimmetje.RoodCore.Main
commands:
    tokens:
        description: tokens
    xp:
        description: xp
    rp:
        description: rp
    codetim:
        description: codetim
    coderood:
        description: coderood
    swaggergear:
        description: swaggergear
    masstokens:
        description: masstokens